# harness/loop.py
#
# PAR Loop Harness
#
# Orchestrates the Plan-Act-Reflect loop for autonomous code generation.
# This file is pure orchestration — all implementation details live in:
#
#   harness/agent.py       — LLM calls, prompt I/O, PAR phase functions
#   harness/filesystem.py  — output boundary writes and reads
#   harness/skills/        — ShellSkill, GitHubSkill, SkillRegistry
#
# Dependencies:
#   pip install anthropic PyGithub
#
# Required environment variables:
#   ANTHROPIC_API_KEY   — Anthropic API access
#   GITHUB_PAT          — GitHub personal access token (for GitHubSkill)
#   GITHUB_USERNAME     — GitHub username (for GitHubSkill)

import json
import sys
from pathlib import Path
from typing import Optional

# ---------------------------------------------------------------------------
# Local imports
#
# Insert the harness directory into sys.path so sibling modules are
# importable regardless of how loop.py is invoked (directly as a script
# or via python -m harness.loop from the project root).
# ---------------------------------------------------------------------------

sys.path.insert(0, str(Path(__file__).resolve().parent))

from agent import agent_act, agent_plan, agent_reflect, is_done, load_agent_context  # noqa: E402
from filesystem import read_generated_files  # noqa: E402
from skills import build_skill_registry  # noqa: E402

# ---------------------------------------------------------------------------
# Path constants
# ---------------------------------------------------------------------------

PROJECT_ROOT = Path(__file__).resolve().parents[1]
OUTPUT_ROOT = PROJECT_ROOT / "fhir-patient-analysis"


# ---------------------------------------------------------------------------
# Main PAR loop
# ---------------------------------------------------------------------------

def run_loop(
    max_iterations: int = 5,
    output_repo: Optional[str] = None,
    output_repo_description: str = "Generated by PAR loop autonomous coding agent",
    run_black_formatting: bool = False,
):
    """
    Run the Plan-Act-Reflect loop.

    Each iteration:
      1. Plan    — agent produces an implementation plan
      2. Act     — agent writes files to OUTPUT_ROOT
      3. Test    — harness runs syntax check and pytest
      4. Reflect — agent evaluates its output against criteria
      5. Commit  — harness commits files to GitHub (if enabled)

    The loop exits when the agent's reflection returns done=True,
    or when max_iterations is reached.

    Args:
        max_iterations:          Hard ceiling on loop iterations.
        output_repo:             GitHub repository name for committing
                                 generated files. Pass None to skip GitHub.
        output_repo_description: Description used when creating the repo.
        run_black_formatting:    If True, runs black before pytest each
                                 iteration. Optional quality-of-life step.
    """
    print("\n" + "=" * 60)
    print("  PAR Loop Starting")
    print("=" * 60)

    registry = build_skill_registry(OUTPUT_ROOT)
    shell = registry.get("shell")
    github_enabled = "github" in registry.available

    # Create the output repository once before the loop begins
    if output_repo and github_enabled:
        registry.get("github").create_repo(output_repo, output_repo_description)

    context = load_agent_context()

    prior_issues = []  # empty on first iteration

    for iteration in range(max_iterations):
        print(f"\n{'=' * 60}")
        print(f"  Iteration {iteration + 1} of {max_iterations}")
        print(f"{'=' * 60}")

        # --- Phase 1: Plan ---
        plan = agent_plan(context)

        # --- Phase 2: Act ---
        agent_act(plan, OUTPUT_ROOT, prior_issues=prior_issues)

        # --- Phase 3: Test (harness-driven, not agent-driven) ---
        if run_black_formatting:
            print("\n--- FORMAT (black) ---")
            shell.run_black()

        print("\n--- SYNTAX CHECK ---")
        syntax_output = shell.check_syntax()
        print(syntax_output)

        print("\n--- TEST (pytest) ---")
        pytest_output = shell.run_pytest()

        # Prepend syntax check results so the Reflect agent sees both.
        # If there are syntax errors, pytest collection will fail anyway;
        # the compiler output gives the agent precise line numbers.
        combined_test_output = syntax_output + "\n\n" + pytest_output

        # --- Phase 4: Reflect ---
        generated_files = read_generated_files(OUTPUT_ROOT)
        reflection = agent_reflect(context, generated_files, combined_test_output)

        prior_issues = reflection.get("issues", [])
        print("\n--- REFLECTION SUMMARY ---")
        print(json.dumps(reflection, indent=2))

        # --- Phase 5: Commit (harness-driven, only on success) ---
        task_is_done = is_done(reflection, iteration)

        if task_is_done and output_repo and github_enabled and generated_files:
            commit_message = "feat: initial FHIR patient data loader and analyzer"
            registry.get("github").commit_files(
                repo_name=output_repo,
                files=generated_files,
                commit_message=commit_message,
            )

        # --- Loop control ---
        if task_is_done:
            print("\n✓ Agent reports task complete.")
            break
        else:
            issues = reflection.get("issues", [])
            if issues:
                print("\n  Issues to address in next iteration:")
                for issue in issues:
                    print(f"    - {issue}")
            print("\n↻ Continuing to next iteration.")

    else:
        print("\n⚠  Max iterations reached without completion.")

    print("\n" + "=" * 60)
    print("  PAR Loop Complete")
    print("=" * 60 + "\n")


# ---------------------------------------------------------------------------
# Entry point
# ---------------------------------------------------------------------------

if __name__ == "__main__":
    run_loop(
        max_iterations=5,
        output_repo=None,           # e.g. "fhir-patient-analysis"
        run_black_formatting=False,
    )
